### ISSUE TITLE
[USABILITY] Family Members Screen should be scrollable

### ISSUE THREAD

**Issue by joegrohens** [rokwire/safer-illinois-app#0]
**Describe the usability issue**
In Settings > Family Members 
If the list of family members is longer than one screen, the screen cannot be scrolled, and buttons cannot be accessed.

**Device** 
iPhone 11, Google Pixo

**Version**
Safer Illinois v 2.9.21

![IMG_0638](https://user-images.githubusercontent.com/66988329/114190454-f0002580-9910-11eb-9b26-9f2b26ed9c54.jpeg)

**Comment by mihail-varbanov** [comment]
Fixed in version 2.10.17.

**Comment by joegrohens** [comment]
Verified fixed in TestFlight version 2.10.18
