### ISSUE TITLE
[FEATURE] update next steps and health history for Contact Trace Quarantine

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#122]
The Next Steps shown to users after being placed in quarantine by CUPHD contact tracers are "Stay at home and avoid contacts."

The event added to the Health History is titled `Action Required` and has text entered by CUPHD, which has been left blank on occassion.

Please change the Next Steps for Contact Trace Quarantine  to:
> You have been placed in mandatory isolation.
>
> * Stay home. Do not go to work, school, or public areas.
> * Separate yourself from others in your home.
> * Contact Champaign-Urbana Public Health District immediately at coronavirus@c-uphd.org
> * Get tested on the fourth day following exposure to see if you have developed the disease.
> * You can leave quarantine on the fifteenth day after exposure.
>

For the button in Next Steps window and Home panel:

> [More Info: Quarantine and Isolation](https://covid19.illinois.edu/health-and-support/quarantine-and-isolation/)

Update the related Health History item to:
> **Title:** Quarantine
> 
> **Provider(like the provider on test results):** Champaign-Urbana Public Health District
>
> **Body**: {{text entered by CUPHD in admin interface}}
>

**Comment by pmarkhennessy** [comment]
@isaac-galvan believe we did these for 2.5.6++ please check and close etc

**Comment by isaac-galvan** [comment]
Thank you. Looks great.
