### ISSUE TITLE
[REQUEST] Exposure notification workflow, text and protocol review requested

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/safer-illinois-app#124]
**Describe the bug**
Please review exposure notification screen workflow, text and protocols.

**To Reproduce**
Exposure notification between "red, positive" user and "yellow, negative user"

**Expected behavior**
Unsure what the expected behavior should be.
1. Should it say "exposure notification" instead of "contact trace" in Event history?
2. "Next steps" don't seem correct, after the exposure event happened on Sept 4th, next steps say "Take COVID-19 test after September 8, ASAP"
3. Should "Next Steps" include protocols from CUPHD - like isolate for 4 days and for two negative tests?

**Screenshots*
![next steps](https://user-images.githubusercontent.com/32363320/92283156-e919bc00-eec4-11ea-8686-242f797f8f23.PNG)
![Contact_Trace_Event_History](https://user-images.githubusercontent.com/32363320/92283173-f0d96080-eec4-11ea-853e-5e48fc135fc1.PNG)
![Contact_Trace_History](https://user-images.githubusercontent.com/32363320/92283187-f767d800-eec4-11ea-9411-a2a8a18453ab.PNG)
![Exposure_Screen_Capture](https://user-images.githubusercontent.com/32363320/92283191-fa62c880-eec4-11ea-81fb-b1f885ffdff5.PNG)

**Smartphone (please complete the following information):**
 - Android Moto 7 - Android 10

**Additional context**

**Comment by pmarkhennessy** [comment]
@ToddNelson will take this us with JP...
