### ISSUE TITLE
[BUG] iOS - XS Max - Text contents are Shattered in the app

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#148]
**Describe the bug**
Text contents are Shattered on the Home screen and status screen of the Safer Illinois app

**To Reproduce**
1. Install the app
2. Complete the onboarding process and verify the identity as a Faculty
3. The app displays the home screen

**Actual Behaviour**
Text contents are Shattered on the Home screen and status screen of the Safer Illinois app

**Expected behavior**
Contents should display clearly without breaking.

**Screenshots**
![broken text 1](https://user-images.githubusercontent.com/26231179/93096877-89f93b80-f66a-11ea-997d-2699902f0243.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone - XS Max]
 - OS: [e.g. iOS13.6.1]
 - App Version [e.g. 2.5.5]

**Comment by mdryankov** [comment]
@Priyaravi8 I'm unable to reproduce it. Could you please put more details like Regional settings (everything that may be related and it's not a default setting for the device)?

**Comment by braeden** [comment]
@mdryankov Looks like some people can repro here: https://www.reddit.com/r/UIUC/comments/iuoveh/does_anyone_elses_safer_illinois_app_always_look

Might be worth dm-ing those individuals!

**Comment by mdryankov** [comment]
@Priyaravi8  @braeden The steps for reproduction are still not clear. We're with tight hands without steps. 

Assign back to @Priyaravi8

**Comment by Priyaravi8** [comment]
The user has not reproduced this issues anymore.
