### ISSUE TITLE
[BUG] Map of the test location is not loaded in the app

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#149]
**Describe the bug**
Map of the test location is not displayed to the user

**To Reproduce**

1. Install the safer Illinois app
2. Complete initial onboarding steps of the app
3. The user verifies as student
4. Tap on Find location button on the Home screen
5. Tap on the location icon of any of the test location

**Actual result**
The app displays a blank white screen on the Map screen

**Expected behavior**
A map of the selected location should display on the screen.

**Screenshots**
![map](https://user-images.githubusercontent.com/26231179/93097652-739faf80-f66b-11ea-881d-acca6a06926b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.5.8]

**Comment by mdryankov** [comment]
![device-2020-09-16-144653](https://user-images.githubusercontent.com/7037018/93333136-89f46980-f82b-11ea-88f5-a2d34f9e82ce.png)
@Priyaravi8 I tested with 2.6.5 (pinned to prod) and I'm unable to reproduce it. Could you please verify your side and close it if it's fine. Thanks.

**Comment by Priyaravi8** [comment]
Retested the app in version 2.6.13. This issue is fixed.
