### ISSUE TITLE
Display an error message to the user who submits the symptoms without checking any list on the Symptom Check-in

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#174]
**Describe the bug**
Users can submit the Symptom check-in without selecting any of the symptoms on the displayed list.

**To Reproduce**
1. Install Safer Illinois app
2. Complete the onboarding process
3. Tap on "Symptom Check-in" on the Home screen of the Safer Illinois app
4. Tap on the Submit button without selecting any of the symptoms on the displayed list.

**Actual Result** 
"Your Symptoms have been processed" message is displayed, although the user didn't select any of the symptoms lists. 
Also, for this scenario, Self-reported symptoms are displayed on the event history screen.

**Additional Note -** 
"Open channel for BIP" is also displayed on the screen.

**Expected behavior**
Display an error message to the user who submits the symptoms without checking any list on the Symptom Check-in

**Screenshots**
![Symptoms submit](https://user-images.githubusercontent.com/26231179/93786463-f806ab00-fbf4-11ea-9fc2-6e97b656c6fb.png)

![symptom history](https://user-images.githubusercontent.com/26231179/93793993-28eade00-fbfd-11ea-9f97-2bc30ba4a415.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android, iOS]
 - Version [e.g. 2.5.8]

**Comment by mdryankov** [comment]
Fixed

**Comment by pmarkhennessy** [comment]
@Priyaravi8 fixed in 2.6.15

**Comment by Priyaravi8** [comment]
Retested this issue. It is fixed.
