### ISSUE TITLE
[BUG] Fix log data

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/safer-illinois-app#178]
**Describe the bug**
Fix logs coming from the Safer Illinois app.

CC: @wryanthomas

1. `session_uuid` needs to be set and included in all log entries from the app. Since these are not tied to any user account, it would continue to preserve the anonymous nature of the logs while helping in debugging general issues. As described in this comment (https://github.com/rokwire/safer-illinois-app/issues/178#issuecomment-700166505), there are many log entries without `session_uuid` in the data.
2. Currently, `user_uuid` is anonymized for most log entries. It needs to be anonymized for the remaining of the log entries from the app.

**Smartphone (please complete the following information):**
 - Device: Android and iPhone
 - Version 2.5.8

**Comment by wryanthomas** [comment]
For logs from user activity in profiles building block, I agree user_uuid is essential. Also...

I recommend session_uuid be included in *every* log generated from user behavior -- not just from profile activity.

**Comment by mihail-varbanov** [comment]
This is not a bug. This behavior is by purpose:

**UIUC Monday 2020/06/08**

> 1.2 Analytics - any panel/page views of any COVID-19 should have no user info UUID, UIN, name etc. These should be totally anonymous.

FYI, there is another restriction for analytics health events content. We display only current timestamp for these events and omit any other default parameter like UUID, GPS location, device model or whatever.

**UIUC Friday 2020/06/12**

> 3.1 I am wondering if you would be able to fix the issues pointed out in the attached Analytics review: COVID Logging Revision.docx

> The main need is to remove all the context information(uuid, location, device info, etc) from most of the health event logs plus a couple other small changes. Here’s the examples of current logs and what changes are needed.

CC @pmarkhennessy.

**Comment by wryanthomas** [comment]
First, let me suggest that logging a session_uuid would sidestep this issue.

Secondly, my understanding is that Sandeep's request is for Rokwire app, not Safer Illinois app. By abstraction, should we not exclude logging user_uuid (or obfuscate it) whenever app_id=edu.illinois.covid?  (Isn't this already being done?)
________________________________

**Comment by mihail-varbanov** [comment]
Since the issue is created in safer-illinois-app repo my assume is that Sandeep's request is for Safer app.

Also, Safer app logs "session_uuid" properly in my opinion.

**Comment by sandeep-ps** [comment]
Yes, this was for Safer Illinois app, but I can see user_uuid values in some incoming log data. It's anonymized for some and set to null for others. I thought it was missing in certain logs. If user_uuid needs to be completely removed/anonymized, please do so. Also, app_id value (edu.illinois.covid) is missing for logs coming from some log data for Safer Illinois app.

**Comment by sandeep-ps** [comment]
@wryanthomas, as discussed, there is a similar task for Illinois app. I will create that today.

**Comment by wryanthomas** [comment]
> Yes, this was for Safer Illinois app, but I can see user_uuid values in some incoming log data. It's anonymized for some and set to null for others. I thought it was missing in certain logs. If user_uuid needs to be completely removed/anonymized, please do so.

Here is a report (time range = yesterday) showing all instances of user_uuid (this may not be 100% complete -- this field may not be captured fully from logs, especially among non-JSON log formats).

Where user_uuid is greater than event count, it is because the JSON is providing multiple user_uuid values per event.

sourcetype | user_uuid_event_count | all_events
_json | 0 | 135360
access_combined | 0 | 9780
aws:cloudfront:accesslogs | 0 | 76071
aws:cloudtrail | 0 | 896569
aws:cloudwatch | 0 | 349090
aws:cloudwatchlogs:vpcflow | 0 | 12422251
aws:elb:accesslogs | 23554 | 799383
aws:s3:accesslogs | 0 | 125036
illinois:rokwire:app-config | 0 | 26791
illinois:rokwire:appconfig-covid | 0 | 26115
illinois:rokwire:auth | 0 | 210
illinois:rokwire:converge | 57 | 960
illinois:rokwire:events | 0 | 47558
illinois:rokwire:events-manager | 0 | 10890
illinois:rokwire:healthservice | 0 | 374217
illinois:rokwire:image | 0 | 17277
illinois:rokwire:locationservice | 0 | 16160
illinois:rokwire:logging | 748529 | 764422
illinois:rokwire:profile | 53815 | 50557
illinois:rokwire:sports | 0 | 24481
illinois:rokwire:talent-chooser | 0 | 131565
illinois:rokwire:transportation | 0 | 15673
linux_audit | 0 | 1369
linux_messages_syslog | 0 | 2454
ossec_log | 0 | 71

**Comment by wryanthomas** [comment]
> Also, app_id value (edu.illinois.covid) is missing for logs coming from some log data for Safer Illinois app.

I'm suspecting (but could be wrong, of course) that the app_id value is something we should look for in sourcetypes that start illinois:rokwire. Here's a report (time range = yesterday) of app_id existence:

**sourcetype | app_id_values | app_id_event_count | all_events**
illinois:rokwire:app-config |   | 0 | 26791
illinois:rokwire:appconfig-covid |   | 0 | 26115
illinois:rokwire:auth |   | 0 | 210
illinois:rokwire:converge |   | 0 | 960
illinois:rokwire:events |   | 0 | 47558
illinois:rokwire:events-manager |   | 0 | 10890
illinois:rokwire:healthservice |   | 0 | 374217
illinois:rokwire:image |   | 0 | 17277
illinois:rokwire:locationservice |   | 0 | 16160
illinois:rokwire:logging | edu.illinois.covid | 502687 | 764668
illinois:rokwire:profile |   | 0 | 50557
illinois:rokwire:sports |   | 0 | 24481
illinois:rokwire:talent-chooser |   | 0 | 131565
illinois:rokwire:transportation |   | 0 | 15673

**Comment by sandeep-ps** [comment]
> However, I find it hard to believe that the only logs from Safer Illinois are in this one log source. (Is that true?)

So, as I understand it, the direct logs from the "Safer Illinois" app come through the logging building block and will have the source illinois:rokwire:logging. "Illinois app" logs also follows a similar pattern except that it will have different app_id.

**Comment by wryanthomas** [comment]
"direct logs from the 'Safer Illinois' app come through the logging building block and will have the source illinois:rokwire:logging." That would match what I'm seeing.

However, regarding your statement "'Illinois app' logs also follows a similar pattern except that it will have a different app_id." Currently, the only events that have an app_id field (regardless of value) are those where the value is "edu.illinois.covid". (I.e., Safer Illinois logs in illinois:rokwire:logging.) Note the app_id report from my previous post. I.e., you can only look for "Illinois" app logs by app_id by looking for where app_id is NULL or NOT "edu.illinois.covid". This may be acceptable, but just wanted to state what I'm seeing and note how it is different from what you stated.  It does seem like it would be preferrable to have app_id for Illinois app ... but that's because it's not clear to me which sourcetypes (e.g., infrastructure sources) shouldn't be expected to have app_id.

**Comment by wryanthomas** [comment]
Regarding events in illinois:rokwire:logging that do not have session_uuid, here is a breakdown by action, name, page:

This is most relevant to the counterpart Rokwire case, but given that event.name is always 'health', thought it _might_ be relevant here too:

**sourcetype | event.action | event.name | event.page | values(app_id) | values(session_uuid) | session_uuid_event_count | all_events**
-- | -- | -- | -- | -- | -- | -- | --
illinois:rokwire:logging | action_processed | health | Covid19HistoryPanel |   | - | 48 | 48
illinois:rokwire:logging | action_processed | health | Covid19InfoCenterPanel |   | - | 1 | 1
illinois:rokwire:logging | action_processed | health | Covid19StatusPanel |   | - | 58 | 58
illinois:rokwire:logging | action_processed | health | Covid19TestLocationsPanel |   | - | 1 | 1
illinois:rokwire:logging | action_processed | health | RootPanel |   | - | 502 | 502
illinois:rokwire:logging | check_exposures | health | Covid19AddTestResultPanel |   | - | 7 | 7
illinois:rokwire:logging | check_exposures | health | Covid19CareTeamPanel |   | - | 1 | 1
illinois:rokwire:logging | check_exposures | health | Covid19HistoryPanel |   | - | 345 | 345
illinois:rokwire:logging | check_exposures | health | Covid19InfoCenterPanel |   | - | 23 | 23
illinois:rokwire:logging | check_exposures | health | Covid19NextStepsPanel |   | - | 14 | 14
illinois:rokwire:logging | check_exposures | health | Covid19StatusPanel |   | - | 464 | 464
illinois:rokwire:logging | check_exposures | health | Covid19StatusUpdatePanel |   | - | 165 | 165
illinois:rokwire:logging | check_exposures | health | Covid19SymptomsPanel |   | - | 2 | 2
illinois:rokwire:logging | check_exposures | health | Covid19TestLocationsPanel |   | - | 181 | 181
illinois:rokwire:logging | check_exposures | health | Covid19WellnessCenter |   | - | 3 | 3
illinois:rokwire:logging | check_exposures | health | OnboardingUpgradePanel |   | - | 7 | 7
illinois:rokwire:logging | check_exposures | health | RootPanel |   | - | 7457 | 7457
illinois:rokwire:logging | check_exposures | health | SettingsHomePanel |   | - | 23 | 23
illinois:rokwire:logging | check_exposures | health | WebPanel |   | - | 1 | 1
illinois:rokwire:logging | contact_trace_processed | health | Covid19StatusPanel |   | - | 1 | 1
illinois:rokwire:logging | contact_trace_processed | health | Covid19StatusUpdatePanel |   | - | 1 | 1
illinois:rokwire:logging | contact_trace_processed | health | RootPanel |   | - | 4 | 4
illinois:rokwire:logging | contact_trace_test | health | RootPanel |   | - | 1 | 1
illinois:rokwire:logging | provider_test_processed | health | Covid19AddTestResultPanel |   | - | 3 | 3
illinois:rokwire:logging | provider_test_processed | health | Covid19HistoryPanel |   | - | 1211 | 1211
illinois:rokwire:logging | provider_test_processed | health | Covid19InfoCenterPanel |   | - | 3 | 3
illinois:rokwire:logging | provider_test_processed | health | Covid19NextStepsPanel |   | - | 2 | 2
illinois:rokwire:logging | provider_test_processed | health | Covid19OnBoardingConsentPanel |   | - | 5 | 5
illinois:rokwire:logging | provider_test_processed | health | Covid19OnBoardingHowItWorks |   | - | 3 | 3
illinois:rokwire:logging | provider_test_processed | health | Covid19OnBoardingIntroPanel |   | - | 2 | 2
illinois:rokwire:logging | provider_test_processed | health | Covid19StatusPanel |   | - | 247 | 247
illinois:rokwire:logging | provider_test_processed | health | Covid19StatusUpdatePanel |   | - | 24 | 24
illinois:rokwire:logging | provider_test_processed | health | Covid19TestLocationsPanel |   | - | 63 | 63
illinois:rokwire:logging | provider_test_processed | health | OnboardingUpgradePanel |   | - | 4 | 4
illinois:rokwire:logging | provider_test_processed | health | RootPanel |   | - | 3028 | 3028
illinois:rokwire:logging | provider_test_processed | health | SettingsHomePanel |   | - | 25 | 25
illinois:rokwire:logging | report_exposures | health | Covid19HistoryPanel |   | - | 2 | 2
illinois:rokwire:logging | report_exposures | health | Covid19OnBoardingIntroPanel |   | - | 1 | 1
illinois:rokwire:logging | report_exposures | health | Covid19StatusUpdatePanel |   | - | 16 | 16
illinois:rokwire:logging | report_exposures | health | Covid19SymptomsPanel |   | - | 1 | 1
illinois:rokwire:logging | report_exposures | health | RootPanel |   | - | 38 | 38
illinois:rokwire:logging | status_changed | health | Covid19AddTestResultPanel |   | - | 3 | 3
illinois:rokwire:logging | status_changed | health | Covid19HistoryPanel |   | - | 136 | 136
illinois:rokwire:logging | status_changed | health | Covid19InfoCenterPanel |   | - | 3 | 3
illinois:rokwire:logging | status_changed | health | Covid19NextStepsPanel |   | - | 2 | 2
illinois:rokwire:logging | status_changed | health | Covid19OnBoardingConsentPanel |   | - | 4 | 4
illinois:rokwire:logging | status_changed | health | Covid19OnBoardingHowItWorks |   | - | 9 | 9
illinois:rokwire:logging | status_changed | health | Covid19OnBoardingIntroPanel |   | - | 13 | 13
illinois:rokwire:logging | status_changed | health | Covid19OnBoardingQrCodePanel |   | - | 40 | 40
illinois:rokwire:logging | status_changed | health | Covid19StatusPanel |   | - | 151 | 151
illinois:rokwire:logging | status_changed | health | Covid19StatusUpdatePanel |   | - | 5 | 5
illinois:rokwire:logging | status_changed | health | Covid19SymptomsPanel |   | - | 10 | 10
illinois:rokwire:logging | status_changed | health | Covid19TestLocationsPanel |   | - | 23 | 23
illinois:rokwire:logging | status_changed | health | OnboardingUpgradePanel |   | - | 2 | 2
illinois:rokwire:logging | status_changed | health | RootPanel |   | - | 1432 | 1432
illinois:rokwire:logging | status_changed | health | SettingsHomePanel |   | - | 27 | 27
illinois:rokwire:logging | status_changed | health | WebPanel |   | - | 1 | 1
illinois:rokwire:logging | symptoms_submitted | health | Covid19SymptomsPanel |   | - | 45 | 45

**Comment by sandeep-ps** [comment]
> However, regarding your statement "'Illinois app' logs also follows a similar pattern except that it will have a different app_id." Currently, the only events that have an app_id field (regardless of value) are those where the value is "edu.illinois.covid". (I.e., Safer Illinois logs in illinois:rokwire:logging.) Note the app_id report from my previous post. I.e., you can only look for "Illinois" app logs by app_id by looking for where app_id is NULL or NOT "edu.illinois.covid". This may be acceptable, but just wanted to state what I'm seeing and note how it is different from what you stated. It does seem like it would be preferrable to have app_id for Illinois app ... but that's because it's not clear to me which sourcetypes (e.g., infrastructure sources) shouldn't be expected to have app_id.

@wryanthomas, yes, you are right. Illinois app needs to send app_id value in its logs. What I meant is that for both the apps, the clickstream log data flows through the logging building block and they will have different app_id values when these issues are fixed.

**Comment by sandeep-ps** [comment]
Thanks for your inputs @mihail-varbanov and @wryanthomas. I have changed the title and the description based on the discussion. I hope the current description better describe the issue at hand.

**Comment by mihail-varbanov** [comment]
Hi @sandeep-ps,

Thanks for clarifying this stuff!

1. We used to report the actual user uuid only once, in RootPanel appearance. I noticed this yesterday, opened a new [issue](https://github.com/rokwire/safer-illinois-app/issues/216) and (fixed)[https://github.com/rokwire/safer-illinois-app/commit/7b34b546ca35dfdc3a8d7f501e09a92cb6336790] it.

So now we have only 2 options for 'user_uuid' parameter: UUIDxxxxxx or null, if it is not yet generated / retrieved.

2. As long as I understand the restrictions defined for "COVID Logging Revision.docx" (UIUC Friday 2020/06/12 \#3.1) are quite strained. We used to report only timestamp parameter. Now (in version 2.6.15+) I added the following parameters that I believe are not user sensitive: "app_id", "app_version", "session_uuid" and "user_uuid" (as long as it is anonymous or null).

Let me know please if you think that we need some additional change in this model.

**Comment by sandeep-ps** [comment]
Closing this as no additional requests have come in of late.
