### ISSUE TITLE
The user receives COVID test result notification without the user's request.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#201]
**Describe the bug**
COVID test result notification is received without the user's request.

**To Reproduce**
1. Install Safer Illinois app
2. Complete the onboarding process
3. Select the user role as University student and verify their identity
4. Home screen of safer Illinois is displayed. 

**Actual Result**
After installing Safer Illinois app, the COVID test result notification is received without the user's tapping the "Request my Latest test again" button on the Event screen.

**Expected behavior**
The COVID test result notification should display to the user only upon their request.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.5.8]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 Do you have a McKinley test in your history? When the App is installed we send the request automatically and so you would receive a notification. Now, even if the event is in your history we will be sent the event again and that causes a notification. The event will be de-duplicated and so it may appear that nothing has changed. If the above is correct then this is not a bug, it is working as designed.

**Comment by Priyaravi8** [comment]
Closing this issue as it is as designed.
