### ISSUE TITLE
[BUG] Shows positive test result after testing negative

### ISSUE THREAD

**Issue by devcryo** [rokwire/safer-illinois-app#225]
**Describe the bug**
I tested positive for coronavirus the first week of September. After isolating for 10 days, I tested negative. However, the Safer Illinois app continues to say I have a positive test and no building access. I have tested negative multiple times since testing positive. This is also an issue on the UIUC Boarding Pass website.

**Expected behavior**
After testing negative, the positive test should change to a negative one and give you building access back. 

**Screenshots**
![IMG_2522](https://user-images.githubusercontent.com/72035202/94458869-2dbf0d00-017c-11eb-9921-db2ccbf1c63a.jpg)
![IMG_2523](https://user-images.githubusercontent.com/72035202/94458877-30b9fd80-017c-11eb-9cb8-0d41cf898bb7.jpg)
![IMG_2524](https://user-images.githubusercontent.com/72035202/94458885-331c5780-017c-11eb-8ee8-39e57c30d609.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0.1
 - Browser Safari

**Comment by isaac-galvan** [comment]
Hello @devcryo please contact the Technology Services Help Desk to look into your status issue.
Call us: 217-244-7000
Email us: consult@illinois.edu
