### ISSUE TITLE
[DEMAND] Add attribution for idea, designs, and borrowed UI components

### ISSUE THREAD

**Issue by eckels** [rokwire/safer-illinois-app#232]
Add attribution to Cover Me for idea, designs, and UI components. 

We asked to collaborate with testing site workers to provide accurate wait time information a month ago and was promptly shut down by Safer Illinois. Yet, it seems like they’ve gone ahead with our concept and designs. Let us be part of the clout chasing.

Or maybe just ask next time?

The status indicator copying isn't even subtle lol

Our design:
![image](https://user-images.githubusercontent.com/17066287/94627919-64804a80-0284-11eb-8936-95add3272412.png)

Our App:
![image](https://user-images.githubusercontent.com/17066287/94627931-6a762b80-0284-11eb-9314-6f08171e76a8.png)

Your update:
![image](https://user-images.githubusercontent.com/17066287/94628084-b923c580-0284-11eb-8bb2-bb9f3becd6a2.png)

Also some quick comments about the design for ROKWIRE: 
The status indicator is very vague, you should be more specific with what each color means. How long is the wait when the indicator is yellow? Is it 10 minutes? 30 minutes? Users will get confused. This indicator is well implemented in the Cover Me app, perhaps take another look.

**Comment by bhargav-y** [comment]
Yep! Couldn't agree more. Wish the Safer Illinois Team was more accommodating with you :(

**Comment by dilanpatel2000** [comment]
Unbelievable!! For a university whose Computer Science Department preaches proper ethics practices, this is outrageous that the university would so clearly steal the application design OF A STUDENT'S MOBILE APPLICATION. This student also asked to collaborate on testing lines feature with the University, and the University denied this collaboration. I can't believe such a prestigious University would deny student growth and follow such blasphemy with unethical behavior!!!!!
