### ISSUE TITLE
[BUG] The 2 different guidelines is displayed for the same county "Champaign Illinois"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#240]
**Describe the bug**
Two different guidelines are displayed same county "Champaign, Illinois"

**To Reproduce**

1. Install Safer Illinois app
2. Complete the COVID onboarding process
3. User logged in as a University Student on Who are you screen and verified his identity
4. Complete the COVID onboarding steps with Exposure notification and test result Consent to YES
5. COVID set up is done. COVID - 19 screen is displayed
6. Users current status is "Orange, Likely infected"
7. Tap on County Guidelines. County Guidelines - "Champaign, Illinois county" is displayed for status "Orange".
8. Tap on the drop-down arrow displayed next to "Champaign, Illinois county" and select "Champaign, Illinois"

**Actual Result**
Now the county Guidelines is displayed for the status Yellow color

**Expected behavior**
The 2 different guidelines should not display for the same county

**Screenshots**

![CG1](https://user-images.githubusercontent.com/26231179/95095310-84829480-06f0-11eb-9f0f-cd802703b0e5.png)
![CG 2](https://user-images.githubusercontent.com/26231179/95095318-877d8500-06f0-11eb-8beb-e51599adc51c.png)
![Cg 3](https://user-images.githubusercontent.com/26231179/95095321-89474880-06f0-11eb-8d26-aeb6bfbe2072.png)

**Smartphone (please complete the following information):**

Device: [e.g. Android]
 - Version [e.g. 2.6.13]

**Additional context**

**Comment by mdryankov** [comment]
@Priyaravi8 I'm unable to reproduce it with v2.7.1 (Dev & Prod). Could you please provide more details?

**Comment by Priyaravi8** [comment]
I still reproduce this issue and I have sent you a Video file on Slack.

**Comment by mdryankov** [comment]
@Priyaravi8 after deep investigation it seems the issue is fixed by @TodorBachvarov  on 9/28  (v2.6.14)
Please test with a newer version and close the ticket

**Comment by Priyaravi8** [comment]
Retested this issue and it is fixed.
