### ISSUE TITLE
[USABILITY] - Add an external link icon to the Feedback button.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#241]
**Describe the bug**
Add an external link icon to the Feedback button.

**To Reproduce**

1. Download the Safer Illinois app.
2. Complete the initial onboarding process and logged in as a University student.
3. COVID 19 screen is displayed.
4. Tap on the Settings icon.
5. On the Settings screen, tap on Submit Feedback button

**Actual Result**
The submit screen is not part of the Safer app. Adding an external link icon helps the user to understand as the feedback screen is an external screen.

**Expected behavior**
Add an external link icon to the Feedback button.

**Comment by TodorBachvarov** [comment]
Done in version 2.7.7

**Comment by Priyaravi8** [comment]
This issue is resolved.
