### ISSUE TITLE
[USABILITY] Remove duplicate instance of links to Homescreen on Status Card

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/safer-illinois-app#247]
**Describe the usability issue**
There are three different ways shown on the Status card to close and get back to your homescreen. The button with text "Your Covid-19 info center" is no longer relevant (we do not use the term info-center) and is often being cut off by the "X" button at the bottom of the screen. Simplifying this will reduce confusion. 

**To Reproduce**
Click on 'Show Status card'

**Expected behavior**
Only include one way to exit out of the Status card and remove the no longer relevant button with text "Your Covid-19 info center" 

**Screenshots**
![IMG_3656](https://user-images.githubusercontent.com/24440324/95129296-7482a900-0720-11eb-81e5-f51298a2e18f.PNG)

**Comment by dobromirdobrev** [comment]
Done in version 2.7.2.

**Comment by AlliePixo** [comment]
Confirmed change on 2.7.4
