### ISSUE TITLE
[USABILITY] - Safer Illinois - Notification is posted every single minute in iOS

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#255]
**Describe the bug**
Notification is posted every 1 minute in iOS. Due to the notification phone battery is drained so fast.

**To Reproduce**

Install the Safer Illinois app in iOS
Complete the initial onboarding and COVID onboarding process with Exposure notification ON
User successfully see the COVID screen
Actual Result
Notification is posted on the device every single minute and due to that issue battery is drained so fast

**Expected behavior**
Battery should not drain so fast. Also, the user is not expecting notification every single minute.

Smartphone (please complete the following information):

Device: [e.g. iPhone]
-App Version [e.g. 2.6.13]

**Comment by isaac-galvan** [comment]
@Priyaravi8 that is expected and required behavior of the exposure notification system when it runs in the background. Please see [Illinois KB: Safer Illinois, Exposure Notifications](https://answers.uillinois.edu/illinois/page.php?id=104692).

If you have suggestions to update that page, let's talk about them.
