### ISSUE TITLE
[Enhancement] Modify messages on Care Team Cards

### ISSUE THREAD

**Issue by joegrohens** [rokwire/safer-illinois-app#269]
**Is your feature request related to a problem? Please describe.**
Some changes requested by Provost and Bill Sullivan Care Team cards.

Home Page > Your Care Team

**Describe the solution you'd like**
There are two versions (or states) of the card: Non-student version and Student version.

_For BOTH Versions,_ modify or insert the following sentences. See attached PDF for exact location.
[Care Team Card text updates to GitHub.pdf](https://github.com/rokwire/safer-illinois-app/files/5352321/Care.Team.Card.text.updates.to.GitHub.pdf)

[1] Help When You Need It

[2] Reach out to someone on your COVID-19 care team. They’re here to help.

[3] In case of an emergency, call 911.

[4] Insert New Section:
Each contact name should embed the url provided. 

**Mental Health**

Counseling Center  [link to: https://www.counselingcenter.illinois.edu/ ]

 McKinley Mental Health Program
[link to: https://www.mckinley.illinois.edu/medical-services/mental-health] 

Virtual Counseling  [link to: https://www.telehelp4students.com/ ]  (Requires UnitedHealthcare Student Resources coverage.)

_For Non-Student Version Only:_
[5] Insert New Paragraph:
  If you already have a local primary care provider, contact them immediately.

**Comment by joegrohens** [comment]
Update:

The link to Counseling Center now has an anchor tag. Let's use it instead.

New link below:
Counseling Center  [link to: https://www.counselingcenter.illinois.edu/#quicklinks]

Thanks!

**Comment by joegrohens** [comment]
@TodorBachvarov 
In reviewing the previous commit, I saw two issues with the URLs.

1. - The URL https://www.mckinley.illinois.edu/medical- services/mental-health has a space after the hyphen that should be removed.
2. - The Counseling Center link should be updated to include anchor tag. 
Counseling Center  [link to: https://www.counselingcenter.illinois.edu/#quicklinks]

Thank you.

**Comment by joegrohens** [comment]
There are two issues with the implementation of the above changes to the Your Care Team panel in production build 2.8.11. (I am currently testing the apk sent by JP on Slack today.)

1. The phrase "In case of an emergency, " is printed twice in the "call 911" paragraph.
![Screenshot_20201105-002607](https://user-images.githubusercontent.com/66988329/98287121-88613b00-1f6a-11eb-98d2-77364fd52006.png)

2. Under the Mental Health accordion, there is one minor problem.

- **Counseling Center.** This link displays the correct page, but the page does not scroll to the #quicklinks anchor tag.  (The URL is correct in the .dart file. And this is a minor issue. Does the app not have the ability to interpret anchor tags?)

The other two links - "McKinley Mental Health Program", and "Virtual Counseling" - are fine.

**Comment by joegrohens** [comment]
The following statement has still not been added to the Care Team card:
**"If you already have a local primary care provider, contact them immediately."**

This statement should be displayed for non-student users only. 
The desired location for this new paragraph is immediately below the "call 911" statement. 

To see where, look at item [5] in this PDF [Care Team Card text updates to GitHub.pdf](https://github.com/rokwire/safer-illinois-app/files/5352321/Care.Team.Card.text.updates.to.GitHub.pdf).

**Comment by TodorBachvarov** [comment]
Fixed
