### ISSUE TITLE
[BUG] Can't retrieve prior test result after submitting self-symptoms check.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/safer-illinois-app#270]
**Describe the bug**
It's possible that this is correct behavior, but it is a change since version 2.5.8.

After submitting self-reported symptoms, my health status changed to Orange. I requested prior test results. No prior test result was sent.

In the past this would have resulted in a return to my status from before I self-reported symptoms. (And I used it that way to test screens.)

**To Reproduce**
1. Safer Illinois Home > Symptom Check-in 
2. Select a bunch of COVID-consistent symptoms. Turn status Orange.
3. Home > View Health History > Request my latest test again

**Expected behavior**
Receive previous PCR test result.

**Actual behavior**
No test results were received after many hours.

**Smartphone (please complete the following information):**
 - Device: [ iPhone 11]
 - OS: [ iOS 14.0.1]
 - Version [2.6.13]

**Additional context**
Same thing happens on Android beta version 2.7.4

**Comment by pmarkhennessy** [comment]
@joegrohens Tests are in date/time order so if retrieving your test results is an old test then the symptoms will "trump" the old test.

If this is still a bug then let me know.
