### ISSUE TITLE
Update email address for Contact Trace events (and any other screens using the ShieldTeam30 address)

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/safer-illinois-app#277]
Please replace any email contacts directed to Shield Team 30 to the Wellness Center, they are better equipped to handle these requests.

COVID Wellness Answer Center <covidwellness@illinois.edu>

![image](https://user-images.githubusercontent.com/32363320/95596718-5dd79d00-0a13-11eb-8fe4-a5eba86edd91.png)

**Comment by pmarkhennessy** [comment]
@ToddNelson This is done in Safer 2.7 - if I need to do earlier versions let me know

**Comment by ToddNelson** [comment]
Thanks!
