### ISSUE TITLE
[Usability]Please provide more information about the color on the test location wait time

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#279]
**Describe the usability issue**
Please provide more information about the **color** on the test location wait time so the user will understand what the color indicates.

**To Reproduce**

1. Install Safer Illinois app
2. Complete onboarding steps
3. Select the role of University student and verify his identity
4. Tap on "Find test location" on the Safer Illinois Home screen
5. On the Test Locations screen, Choose "McKinley Health Center/SHIELD" from the provider drop-down list
6. Test location centers are displayed with color code wait time 

**Actual Result**
No information is provided about the **color** displayed on the test location wait time

**Expected behavior**
Please provide more information about the **color** on the test location wait time so the user will understand what the color indicates.

![color code](https://user-images.githubusercontent.com/26231179/95630734-f720a680-0a47-11eb-9f6e-5c865a097352.png)

**Smartphone (please complete the following information):**

Device: [e.g. iPhone and Android]
Version - 2.7.4

**Comment by pmarkhennessy** [comment]
@TodorBachvarov Please make the wait times show: 

Green = Short Wait Time
Orange - Medium Wait Time
Red = Long Wait Time

**Comment by Priyaravi8** [comment]
This issue is resolved.
