### ISSUE TITLE
User is not able to Sign out successfully by tapping the Sign-out button on Personal Info screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#303]
**Describe the usability issue**
User is not able to Sign out successfully by tapping the Sign-out button on the Personal Info screen

**To Reproduce**

1. Install safer Illinois
2. Complete onboarding process
3. Select University student and verify his identity with users Netid
4. Complete the Consent steps
5. Safer Illinois home screen is displayed
6. Navigate to Settings screens by tapping the setting icon on the Home screen
7. Proceed to the Personal Info screen by tapping on the Personal Info link on the Settings screen
8. On the Personal Info screen, tap on the "Sign Out" button and "Yes" to the pop-up for Sign out.

**Actual Result** 
Once the user confirms to Sign out, the Personal Info screen still displays user information without a Signout confirmation message.

**Expected behavior**
The app should take back to the Setting screen once the user confirms to sign out

Device: [e.g., iPhone and Android]

**Comment by mdryankov** [comment]
Fixed

**Comment by Priyaravi8** [comment]
This issue is resolved
