### ISSUE TITLE
[USABILITY] Add translations for Next Steps

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#308]
**Describe the usability issue**
Translations are not available for the messages displayed in the Next Steps areas. It seems these are hard-coded in English in the rules file.

**To Reproduce**

1. Change your OS language to Español.
2. Open Safer Illinois to the Home page.
3. The contents of the Next Steps section under your Health are always in English.

**Screenshots**

![safer next steps español](https://user-images.githubusercontent.com/11352701/96514928-09f66080-122a-11eb-80f8-4cabe7dcb7fe.png)

Smartphone (please complete the following information):

Device: Google Pixel 3a
OS: Android 11

**Comment by pmarkhennessy** [comment]
@mihail-varbanov I think this is already in your re-write list, but we need to add languages to the rules. Perhaps like in assets/dining.

**Comment by mihail-varbanov** [comment]
Fixed in version 2.8.3
