### ISSUE TITLE
[BUG] Unable to log in with iOS Default Browser changed

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#315]
**Describe the bug**
Users cannot log in with NetID if the Default Browser is not set to Safari in iOS 14.

**To Reproduce**
1. Install Firefox or Chrome for iOS
2. Go to iOS Settings > Safari > Default Browser App, and set it to Firefox or Chrome
3. Install Safer Illinois and go through the setup
4. Tap on "Log in with NetID" and nothing happens

The "Connect your NetID" button in Safer Illinois Settings screen also has this issue.

**Expected behavior**
Expect to proceed to the login gateway in the default browser and let the user complete logging in.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 and iPhone SE
 - OS: iOS 14
 - Browser: Chrome and Firefox
 - Version: Safer Illinois 2.7.4

**Comment by mdryankov** [comment]
Fixed in 2.8.2

**Comment by isaac-galvan** [comment]
Works well. Thank you!
