### ISSUE TITLE
[BUG] Cannot confirm one time code

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#379]
**Describe the bug**
On an iPhone SE, I cannot confirm the one-time code sent via sms. The code input and submit button are not presented and blocks setup. I cannot see the code while I enter and cannot tap submit.  The keyboard is blocking them.

**To Reproduce**
1. Start Safer Illinois setup
2. Choose Capitol Staff
3. Enter a phone number

**Expected behavior**
The screen can be scrolled so the code input and submit button can be seen.

**Screenshots**
![IMG_0074](https://user-images.githubusercontent.com/11352701/98379692-32919f00-200d-11eb-907a-d0e0efe64827.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (1st gen)
 - OS: iOS 14.0
 - Safer Illinois Version 2.8.11

**Additional context**

**Comment by pmarkhennessy** [comment]
Fixed in 2.8.13 and above

**Comment by pmarkhennessy** [comment]
Sorry now 2.9++
