### ISSUE TITLE
[BUG] iOS notification check - action after selecting notification

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/safer-illinois-app#380]
**Describe the bug**
Bill is reporting receiving notification on his iPhone, when he selected the notification he was taken to the Safer app but couldn't seen any more details about the notification - just opened the app with the notification disappearing.

**To Reproduce**
1. Illicit a new notification for iOS
2. Click on notification
3. Does it take you to the notification/more information?

**Expected behavior**
Expect to see more information about the notification after selecting it.

**Comment by pmarkhennessy** [comment]
@ToddNelson This is not a bug IMHO. The notification was sent without a deep link. Safer supports 2 deep links:

1 Open App into history
2 Open App into status card

There is an issue in Firebase console where Flutter in iOS does not respond to a deep link but it works in Android.

Sending deep links in code does work in both OS.

**Comment by ToddNelson** [comment]
Let Bill know, closing issue for now.
