### ISSUE TITLE
[BUG] inconsistent masking on phone number when confirming code

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#388]
**Describe the bug**
The masking of the phone number on the one-time code entry page is inconsistent.

**To Reproduce**
1. Install Safer 2.8.11
2. Choose Capitol User
3. Enter a valid phone number that is not in the roster
4. Retrieve and enter the one-time code
5. The message "phone number verified by does not exist in authorized users" shows, as expected
6. The masking changes from  ********** to ********8783 (last four digits of the phone number entered)
7. Go back one screen the and change to a rostered phone number then press Next
8. The masking still shows the ********8783 even though that is not the phone number entered in the previous screen

**Expected behavior**
The masking should stay consistent.  If it does mean to show the last four numbers of the phone, it should show the correct last four if the user needs to change it after the first login try.

**Screenshots**
![Screenshot (Nov 11, 2020 8_52_48 AM)](https://user-images.githubusercontent.com/11352701/98830793-6c451a00-2400-11eb-9cb2-c19aa8f49e1f.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.8.11

**Comment by pmarkhennessy** [comment]
@isaac-galvan The masking has been removed in 2.9+ (as per instructions from JP)
