### ISSUE TITLE
[BUG] Name missing from Status card for roster user

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#389]
**Describe the bug**
The name is missing when logged in using phone verification for a roster user.

**To Reproduce**
1. Install Safer 2.8.11
2. Login using rostered phone number
3. Open status screen and no name is presented

**Expected behavior**
My name from the roster should be displayed.

**Screenshots**
![Screenshot (Nov 11, 2020 7_02_37 PM)](https://user-images.githubusercontent.com/11352701/98881869-91617900-2450-11eb-8b1e-4e37ae7dd9f6.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.8.11

**Comment by pmarkhennessy** [comment]
@isaac-galvan There is no name in the Roster data

**Comment by pmarkhennessy** [comment]
@isaac-galvan We have added Name to the Roster Data - should be available in 2.9+
