### ISSUE TITLE
No test results pushed to Safer

### ISSUE THREAD

**Issue by RokBill** [rokwire/safer-illinois-app#393]
**Describe the bug**
I'm using Safer 2.8.11 on my iPhone X. I tested this morning at 7am. I got an email from McKinley at 11:40 am with the test restyle (negative). It is 4:15pm now and I still do not see the results in Safer. I requested my latest results again, but don't see any changes. 

Typically, over the past month, I get results in Safer 30 to 45 minutes prior to the email I get from McKinley.

**Comment by RokBill** [comment]
Sometime in the middle of the night, I got my test result pushed to Safer. It was there at 5am. I wonder if the problem lies with McKinley.

**Comment by pmarkhennessy** [comment]
@RokBill I do not believe this is a client issue either.

**Comment by pmarkhennessy** [comment]
Suggest you close this and reopen if needed
