### ISSUE TITLE
The code "symptoms." displayed along with all the symptoms.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#411]
**Describe the bug**
In Self reported symptoms, the user's symptoms are displayed along with the code "symptoms."

**To Reproduce**
1. Install safer Illinois app
2. Complete onboarding steps and verify the user role as "University student"
3. On Safer Illinois Home screen, tap on Symptom Check-in
4. Tap on the submit button once the user check on the listed symptoms

**Actual result**
Home screen and View Health history screen - the user's symptoms are displayed along with the code "symptoms."

**Expected behavior**
The code "symptoms." should not display along with the symptoms

**Screenshots**
![self issues](https://user-images.githubusercontent.com/26231179/99453232-43ce8b80-28ea-11eb-8b74-402c28fb9fe2.png)
![self symptom issues](https://user-images.githubusercontent.com/26231179/99453238-45984f00-28ea-11eb-97f3-b8dd2a4abea1.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]

 - Version [e.g. 2.9.3]

**Additional context**

**Comment by mihail-varbanov** [comment]
FYI, status update panel (Yellow to Orange) had the same problem. These all should be fixed in Safer 2.9.4.

**Comment by Priyaravi8** [comment]
This issue is resolved.
