### ISSUE TITLE
[BUG] Error message and Confirm phone number button overlaps each other

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#418]
**Describe the bug**
One time code verification screen, the confirm phone number button overlapping with the error message

**To Reproduce**
1. Install the new version of safer Illinois
2. Complete the onboarding process of app
3. Select the role "Capitol Staff". 
4. Enter your phone number to proceed. 
5. Enter the code to verify the One time code
6. Error message is displayed if the user phone number is not authorized

**Actual Result**
Error message and Confirm phone number button overlaps each other

**Expected behavior**
Error message and Confirm phone number button should not overlap each other

**Screenshots**
![Error issue](https://user-images.githubusercontent.com/26231179/99558048-ef2e1d80-2988-11eb-90bd-5036c4104d96.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.9.3]

**Comment by pmarkhennessy** [comment]
Fixed in 2.9.4

**Comment by Priyaravi8** [comment]
This issue is resolved.
