### ISSUE TITLE
[Bug] Only the section "Your Health" is displayed on Safer Illinois home screen when user chooses to transfer the QR code later

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#421]
**Describe the bug**
However, the user verifies their identity, only the section "Your Health" is displayed when user choose to transfer the QR code later

**To Reproduce**
1. Install the new version
2. Complete the onboarding steps
3. select the user's role as a **University student** and **verify his identity** / Select as a **Non-Univerity member** and **verify the identity with phone number**
4. Complete covid onboarding  steps
5. On QR Encryption code scree, tap on **Transfer later button**

**Actual Result**
Only the section "Your Health" is displayed on Safer Illinois home screen when the user chooses to transfer the QR code later even though the user role is verified

**Expected behavior**
The app should display all the information on Safer Illinois home screen

**Screenshots**
![safer home](https://user-images.githubusercontent.com/26231179/99693340-dc7f1b80-2a50-11eb-84c4-99d1dd41b0e3.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android and iPhone]
  - Version [e.g. 2.9.4]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 This is the correct behaviour. Without the QRCode we cannot decrypt/encrypt any test data for a user.

**Comment by Priyaravi8** [comment]
Closing as per Mark comment
