### ISSUE TITLE
[USABILITY] Improve Grammar in Status Update String

### ISSUE THREAD

**Issue by joegrohens** [rokwire/safer-illinois-app#454]
The Status Update panel (see screenshot below) has an ungrammatical sentence:

- You were required an action by health authorities

I believe this line is a string in the app.

**Screenshots**
![Screenshot (Dec 13, 2020 9_36_11 PM) sm](https://user-images.githubusercontent.com/66988329/102423827-77770100-3fcf-11eb-92cf-f9186fea2b18.png)

**To Reproduce**
This screen appears automatically when a user opens their app for the first time after their health status has changed.

**Change Text To**

- Health authorities require you to take an action.  
(please include the period)

**Comment by TodorBachvarov** [comment]
Fixed.
