### ISSUE TITLE
[FEATURE] Create Onboarding Disclosure Panel

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/safer-illinois-app#477]
Please add this Disclosure panel to Safer Illinois.

**Comment by isaac-galvan** [comment]
@TodorBachvarov @pmarkhennessy The panel looks great and informative! Please changes references from "UW-Madison" to "UIUC" or "University of Illinois at Urbana-Champaign".  There is also a reference to Safer Community that should be updated to Safer Illinois. Thank you.
