### ISSUE TITLE
[BUG]  App makes attempts (and fails) to log multiple times per second

### ISSUE THREAD

**Issue by budde25** [rokwire/safer-illinois-app#484]
**Describe the bug**
The app repeatedly try to log data and when it fails [501 Not Implemented] it tries again instantly.

**To Reproduce**
Open the app and sign in.
Check app network activity

**Expected behavior**
Logging should not loop on failure.

**Screenshots**
![Screenshot_20210118-201302](https://user-images.githubusercontent.com/16231105/104979416-d7dfd080-59c9-11eb-8b88-9c833be3f7ef.jpg)
![Screenshot_20210118-201315](https://user-images.githubusercontent.com/16231105/104979422-dc0bee00-59c9-11eb-8da9-7dfa9d19938f.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android
 - Browser Firefox
 - Version 2.12 (UW madison)

**Additional context**
Not sure if this is only an issue with UW Madison fork of the app but I was unable to find that source code for that.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, why does "UW madison" issue resides in Safer Illinois repo?

**Comment by budde25** [comment]
Since UW uses a fork they might pull from this upstream repo. Sorry if it doesn't apply to this one just thought I'd report the bug in case.

**Comment by mihail-varbanov** [comment]
This problem is not observed in Safer Illinois app (the upstream repo). I would report this issue in Rokmetro's [repo](https://github.com/rokmetro/safer-app/issues).

**Comment by budde25** [comment]
Thanks for taking a look, unfortunately it looks like that repo is private so I can't file a bug report.

**Comment by pmarkhennessy** [comment]
Not a Rokwire issue
