### ISSUE TITLE
[USABILITY] Bullet number on Disclosure screen needs to be in Bold

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#489]
**Describe the usability issue**
The bullet number on the Disclosure screen needs to be in Bold 

**To Reproduce**

1. Install the safer app
2. Complete onboarding screens of the Safer app
3. Select the role as a University student and verify his identity
4. Proceed with Covid onboarding process.
5. Information Usage Disclosure screen is displayed

**Actual Result**
The bullet number on the Disclosure screen is not visible strongly. 

**Expected behavior**
Update the bullet numbers in bold to make them visible strong.

**Screenshots**
![Bullet number](https://user-images.githubusercontent.com/26231179/105064824-d3a3c980-5a42-11eb-9b6a-e52317050aeb.png)

**Smartphone (please complete the following information):**

Device: [e.g. Android]
App Version : [2.10.10]

Additional context

**Comment by mihail-varbanov** [comment]
Implemented in version 2.10.12.

**Comment by Priyaravi8** [comment]
This issue is resolved
