### ISSUE TITLE
[BUG] Disclosure screen - The word "Location" is duplicated 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#490]
**Describe the bug**
On the Disclosure screen, the word "Location" is duplicated in the 7th bullet point

**To Reproduce**

1. Install the safer app
2. Complete onboarding screens of the Safer app
3. Select the role as a University student and verify his identity
4. Proceed with Covid onboarding process.
5. Information Usage Disclosure screen is displayed

**Actual Result**
The word "Location" is duplicated in the 7th bullet point

**Expected behavior**
Duplicate words should be removed.

**Screenshots**
![Words duplicated](https://user-images.githubusercontent.com/26231179/105067127-051d9480-5a45-11eb-8bdb-1b0ce7be7b22.png)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
App Version : [2.10.10

**Comment by TodorBachvarov** [comment]
Fixed after version 2.10.12

**Comment by pmarkhennessy** [comment]
@Priyaravi8 you will want to check this in 2.9.5 or above (not 2.10++)

**Comment by Priyaravi8** [comment]
Retested this issue with version 2.9.5, its fixed.
