### ISSUE TITLE
[BUG] Link to web page doesn't load

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#512]
**Describe the bug**
Page doesn't load when following link to the Counseling Center.

**To Reproduce**
1. Tap on Your Care Team on the Home screen
2. Expand the Mental Health group and tap on Counseling Center
3. The page doesn't load and shows a spinning icon

**Expected behavior**
The page for the Counseling Center should show

**Screenshots**
![IMG_2728](https://user-images.githubusercontent.com/11352701/106677654-bd3b5900-657e-11eb-940c-c1c802524cb5.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4
 - Version 2.9.4

**Additional context**
There is a space at the start of the url here:
https://github.com/rokwire/safer-illinois-app/blob/2f531cea1db0b78fda7b1ef9a850100860022590/lib/ui/health/HealthCareTeamPanel.dart#L298

**Comment by mihail-varbanov** [comment]
Fixed in version 2.9.11 & 2.10.12

**Comment by isaac-galvan** [comment]
Works great thanks!
