### ISSUE TITLE
[FEATURE] update flutter connectivity plugin

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#519]
**Is your feature request related to a problem? Please describe.**
The version of flutter's `connectivity` plug we use to detect if a user is online also provides access to specific wifi connection information, such as SSID and BSSID. We are being required to disclose how we use SSID and BSSID, even though we are not using it in the app. This is making store submission very difficult.

Newer versions of `connectivity` (>2.0) remove wifi connection information.  Wifi details are now in their own plugin, `wifi_info_flutter`.

Can we update the plugin so we no longer have access to specific wifi information we do not need?
https://pub.dev/packages/connectivity/changelog

**Describe the solution you'd like**
Update the `connectivity` plugin to a newer version that does not have access to specific wifi connection information like SSID and BSSID.

**Comment by mihail-varbanov** [comment]
Fixed in version 2.9.12
