### ISSUE TITLE
[BUG] [URGENT]

### ISSUE THREAD

**Issue by joegrohens** [rokwire/safer-illinois-app#528]
**Describe the bug**
Change to Health Rules required as described in the following SLACK message of Nick Vance (Feb 15 12:11pm)

@npvance2Illinois 

> Hey folks I have an urgent request.
> Dr Parker has drafted new language that after sending some test events today I realized that we have not incorporated into the app’s text for positive-ip and positive-nip events.
> 
> The next steps text is something we can change in the json correct?
> 
> If so can someone please update to the text below.
> 
> Positive-ip
> Your Saliva PCR test shows the VIRUS IS DETECTED. Due to the timing of this collection and the detection of virus, this is considered an INFECTIOUS POSITIVE. You require isolation to prevent viral spread to others. 
> 
> Please self-isolate and you will be contacted by Public Health in the next 24 hours. Please contact the University’s COVID Wellness Answer Center or call 217-333-1900 if you have questions. (edited) 
> 
> Positive-nip
> Your Saliva PCR test shows the VIRUS IS DETECTED in your REPEAT POSITIVE at a NON-INFECTIOUS LEVEL. 
> 
> You are not required to self-isolate unless you have Covid-like symptoms and are directed to do so by your licensed health professional.

**Comment by joegrohens** [comment]
@mihail-varbanov @isaac-galvan 

Mihai -
Isaac pointed out that my pull request is on the develop branch, which targets 2.10. These changes also need to be applied to 2.9. Can they be back-propagated to 2.9 as well?
Joe

**Comment by mihail-varbanov** [comment]
The new strings are acknowledged in source rules JSON and uploaded to the server.

**Comment by joegrohens** [comment]
Changes confirmed. The Spanish and Chinese translation of these strings has also been completed.
