### ISSUE TITLE
[BUG] change NIP result testing interval

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#532]
**Describe the bug**
The testing interval should turn back to normal after getting `postive-nip` result.
Right now it gives yellow/allowed status for 60 days.

**To Reproduce**
1. Add a `positive-nip` event to the health history.
2. User gets yellow/building access allowed status for 60 days. 

**Expected behavior**
The testing interval should be normal for the user, not 60 days.

**Smartphone (please complete the following information):**
 - Version 2.9.12

**Comment by mihail-varbanov** [comment]
Available in version 2.10.

**Comment by isaac-galvan** [comment]
@mihail-varbanov there is an issue with the new rule. cc: @pmarkhennessy 

A user who get's a `positive-NIP` status is not presented with the guidance in the `"positive-nip.step.html"` or `"positive-nip.explanation"` strings

**To Reproduce:**
1. add a `positive-NIP` event to the health history
2. user's status is Yellow. their next steps are 'Monitor your test result'.

**Expected Behavior**
User status is yellow/allowed, but their next steps should be the message in `"positive-nip.step.html"` and `"positive-nip.explanation"`, and their next test date should be based on their assigned testing interval.

**Comment by mihail-varbanov** [comment]
This must be fixed now for dev/test 2.9 and dev/test/prod 2.10.

**Comment by isaac-galvan** [comment]
Looks great. We'll deploy to 2.9 prod tonight.
