### ISSUE TITLE
[BUG] Change in "remove my info" app behavior

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#547]
**Describe the bug**
When using the "Remove my information" button in 2.9.4, the app would reset to the "Get Started" screen. 
In 2.9.12, the app stays on the "Personal Info" page

**To Reproduce**
1. Install Safer Illinois 2.9.12
2. Sign in with NetID
3. Go to Settings, then Personal Info, then tap Remove My Information, then tap Yes to confirm
4. The app remains on the Personal Info screen and doesn't reset to the "Get Started" screen.
5. If the user backs out and signs in with their NetID in the settings screen, they get the "Unable to retrieve user COVID-19 settings" error.

**Expected behavior**
The app should reset to the "Get Started" screen after using "Remove My Information" as in 2.9.4.

**Smartphone (please complete the following information):**
 - Device: iPhone SE (1st Gen) and Pixel 3a
 - OS: Latest iOS and Android
 - Safer Illinois 2.9.12

**Comment by mihail-varbanov** [comment]
This should be resolved in 2.9.16 & 2.10.12.
