### ISSUE TITLE
[BUG] Test location lists are not displayed 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#556]
**Describe the bug**
The app is not displaying the list of test location on Test Locations screen when user choose All Providers

**To Reproduce**
1. Install the safer app
2. Proceed with Onboarding screens
3. Verify the user role as University Student and proceed to Safer Illinois Home screen
4. Tap on the Find test locations button

**Actual Result**
No test location is displayed for All Providers. Also, only "All providers" is available in the drop-down list.

**Expected behavior**
Test locations should display for the selected providers. Also, Mckinley providers should also be added to the drop-down list.

**Screenshots**
![location](https://user-images.githubusercontent.com/26231179/110164543-1d5c2f80-7db7-11eb-8902-2f77ab651a70.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - App Version [e.g. 2.9.17]

**Comment by mdryankov** [comment]
Unable to reproduce. The locations are loaded. 
![device-2021-03-22-141234](https://user-images.githubusercontent.com/7037018/111988562-5582a280-8b19-11eb-88d4-d20cde16154e.png)


Please provide clear steps or close the ticket

**Comment by mihail-varbanov** [comment]
This situation might happen if any of the requests for loading providers or location fails. Versions 2.9.22 and 2.10.13 are updated to display error message in such case, as well as some general cleanup in this was applied.

**Comment by Priyaravi8** [comment]
This issue is resolved
