### ISSUE TITLE
[BUG] iOS - Information Usage Disclosure screen is not displayed in iOS

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#571]
**Describe the bug**
In iOS, Once the App is installed for the first time "Information Usage Disclosure" screen is not displayed before the "Turn on Location Services" screen. But the "Information Usage Disclosure" is displayed on Android.

**To Reproduce**
1. Install the safer App
2. Open the Safer app
3. Tap on the "Get started" button on the splash screen

**Actual result**
Information Usage Disclosure screen is not displayed which is displayed in Android.

**Expected behavior**
The "Turn on Location Services" screen is displayed without displaying the Information Usage Disclosure screen in iOS. 

**NOTE - To avoid confusion between Andriod and iOS users, it's better to have the same set of screens displayed for both Android and iOS users.**

 - Device: [e.g. iPhone 8 plus]
 - OS: [e.g. iOS13.3]
 - App Version [e.g. 2.9.20]

**Comment by isaac-galvan** [comment]
@Priyaravi8 this screen is only required for Android.
