### ISSUE TITLE
[BUG] Building access calculation issue

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#572]
**Describe the bug**
Users are having one extra day of building access granted. This issue was reported by users to help desk.

**To Reproduce**
1. Have a negative test dated March 10. User should have access until March 14 and lose access on March 15.
2. Today, March 15, users still have building access. Next Steps say "Monitor your test results. You will turn orange/access denied if no negative test by Sunday, March 14." March 14 was yesterday.

I tried this in Dev environment with all dates one week back. Users with a negative test on March 3 loses building access on March 8, as expected. 

This suggest the issue may be related to Daylight Savings Time.

**Expected behavior**
Users with a last test date of March 10 should lose access today March 15.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE (1st Gen)
 - OS: iOS 14.5
 - Version 2.9.20

**Additional context**

**Comment by mihail-varbanov** [comment]
Fixed in version 2.9.21

**Comment by sandeep-ps** [comment]
@isaac-galvan, I suppose this is also applicable to Android, right?

**Comment by mihail-varbanov** [comment]
That's right, @sandeep-ps. The fix is in Dart section that affects both Android and iOS.
