### ISSUE TITLE
[BUG] YouTube videos plays when screen locked

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#580]
**Describe the bug**
On Android, a YouTube video embedded in a web page displayed in the app plays in the background if the screen is locked.
Google has asked us to address this as background play of YouTube videos is against their policies.

**To Reproduce**
1. Open Safer Illinois and tap on Your Care Team
2. Expand Mental Health and tap Virtual Counseling
3. Start the YouTube video on that webpage
4. Turn off your screen or exit the app and the video continues to play in the background.

**Expected behavior**
The video should stop playing when the screen is locked or app is closed. Alternatively, open the Virtual Counseling page in another browser installed on the phone.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11
 - Version 2.9.21

**Additional context**
The video stops on screen lock or app close in Firefox and Chrome on Android.

**Comment by mdryankov** [comment]
This fixed both in 2.9.22 & latest versions
