### ISSUE TITLE
[BUG] Many users reporting issues around login/frequent logouts

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/safer-illinois-app#593]
**Describe the bug**
Many users are still reporting login issues or that they are getting logged out frequently.

**To Reproduce**
At this point, it is not clear how to reproduce this issue. Many people are reporting that they cannot log in to the app or are getting frequently logged out. I will update this issue if I get more details on this.

**Expected behavior**
Login and frequent logout issues need to be fixed.

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: iOS and Android
 - Version 2.9.21 and 2.9.22

**Additional context**
Previously there was an issue with Shibboleth, which caused the refresh token to expire within a day. As per the Shibboleth team, this has been resolved. So, after this, if the users log in to the app, the session should continue.

**Comment by dobromirdobrev** [comment]
I was not able to reproduce any logout issues.

**Comment by mdryankov** [comment]
@sandeep-ps @isaac-galvan is it possible to find a concrete user with such issue and his/her analytics log, how often this issue occurs and potential clarity about the steps of reproduction? It would be in great help and detail to identify what's going so wrong.

**Comment by sandeep-ps** [comment]
This was related to a Shibboleth upgrade that took place at the end of March. Closing this issue.
