### ISSUE TITLE
[BUG] iOS - Covid-19 Wellness Center - Email compose window is not opening for the Email id "Covidwellness@illinois.edu"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#601]
**Describe the bug**
Email compose window is not opening for the Email id "Covidwellness@illinois.edu"

**To Reproduce**
1. Install safer app
2. Complete the onboarding steps and navigate to the home screen of the safer app
3. Tap on "Covid-19 wellness Answer Center".
4. Tap on the email id - Covidwellness@illinois.edu

**Actual Result**
Email compose window is not opening for the Email id "Covidwellness@illinois.edu"

**Expected behavior**
Email compose window should open for the Email id "Covidwellness@illinois.edu"

NOTE - It works fine on Android 

**Smartphone (please complete the following information):**
 - Version [e.g. Covid-2.10.18-prod.apk]

**Comment by mihail-varbanov** [comment]
Fixed in version 2.10.20.

**Comment by Priyaravi8** [comment]
Retested this issue and it is fixed in version 210.22
