### ISSUE TITLE
[USABILITY] On Setting screen, Disable Covid-19 section for the user who didn't verify the identity

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#602]
Describe the usability issue
Covid-19 section with Retry button is displayed even though a user proceeded to the home screen of Safer either without connecting the app using Netid and without verifying phone number. 

To Reproduce

1. Install the safer app
2. User role is selected as a University student.
3. User didn't verify his identity. Proceeded further without logging in.
4. Complete the initial onboarding and Covid Onboarding steps.
5. Safer Home screen is displayed. Tap on the Setting icon and proceed to the "Setting" screen

**Actual Result**

1.Covid-19 section with Retry button is displayed even though a user proceeded to the home screen of Safer either without connecting the app using Netid and without verifying phone number.  Also, the Retry button is not working

**Expected behavior**
Disable the Covid-19 section for the user who didn't verify the identity as the Retry button is also not working.

Screenshots
![Retry button](https://user-images.githubusercontent.com/26231179/115608094-6c005300-a2ab-11eb-834c-4612dfd605db.png)

Smartphone (please complete the following information):

Device: [e.g. iPhone and Android]
Version: 2.10.18

**Comment by mdryankov** [comment]
Fixed

**Comment by mihail-varbanov** [comment]
Fixed in version 2.10.20.

**Comment by Priyaravi8** [comment]
Retested this issue in version 2.10.20. This is fixed.
