### ISSUE TITLE
[BUG] With correct date setting, status card displays the pop up message "Your Date & Time is incorrect"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#619]
**Describe the bug**
Though the user has the correct date and time setting in the phone device, the app still displays the pop-up message "Your Date & Time is incorrect" in Status Card.

**To Reproduce**

**NOTE - The user didn't change his date and time in the phone settings. The user has the correct Date and Time on his phone.**

1. Install the safer app.
2. Completed the initial onboarding process.
3. User chose the role of a University Student and verify his identity.
4. Completed the Covid onboarding screen, set up the QR code, and proceed to Safer Home screen.
5. Tap on the Show Status card.

**Actual Result**
Though the user has the correct time and date,  the app still displays the pop-up message "Your Date & Time is incorrect" in Status Card.

**Expected behavior**
The app should not display the pop-up message "Your Date & Time is incorrect" if the user has the correct date and time

**Screenshots**
![Date and time](https://user-images.githubusercontent.com/26231179/116606229-05f07d00-a8f6-11eb-8448-9d22cbbf6ec6.png)

**Smartphone (please complete the following information):**
 - OS: [e.g.Android]
 - Version [e.g. 2.10.22]

**Comment by isaac-galvan** [comment]
I am also having this issue.

**Comment by pmarkhennessy** [comment]
Please retest when the latest health bb has been deployed

**Comment by Priyaravi8** [comment]
Reinstalled version 2.10.22. Retested the issue today. I still reproduce the same issue.

**Comment by Priyaravi8** [comment]
Retested this issue with the latest Health BB. This issue is fixed.
