### ISSUE TITLE
[BUG] Exposure notification frequent vibration

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#641]
**Describe the bug**
In Safer Illinois 2.10.22, when Exposure Notification is turned on, the phone would vibrate one time when the Exposure Notification toggle is changed to On.

In Safer Illinois 2.10.23, when Exposure Notification is on, the phone vibrates every couple of seconds.

**To Reproduce**
1. Install 2.10.23
2. Go through the setup and connect NetID
3. Turn on Exposure Notifications during on-boarding or in the settings panel.

**Expected behavior**
The phone would vibrate one time as it did in 2.10.22.

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.10.23

**Comment by Priyaravi8** [comment]
I am able to reproduce this issue too.

**Comment by dobromirdobrev** [comment]
Fixed in version 2.10.25 and above.

**Comment by Priyaravi8** [comment]
Retested this issue. This issue is fixed in version 2.10.25

**Comment by isaac-galvan** [comment]
Thanks!
