### ISSUE TITLE
[BUG] iOS -  Exposure notification system is not alerting

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#645]
**Describe the bug**
In iOS, the exposure notification alert is not displayed to the user.

**To Reproduce**
1. Install the app
2. Complete the initial onboarding steps
3. Verify the user role as a Univesity student with their identity
4. Complete the covid onboarding steps and make sure the user turns on the Exposure notification

 
**Actual Result**
A notification "Exposure Notification System checking" should appear on the device

**Expected behavior**
In iOS, the exposure notification alert is not displayed to the user.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone]
 - Version [e.g. 2.10.25]

**Additional context**

**Comment by mihail-varbanov** [comment]
I am unable to recreate this problem. The Exposure local notification is displayed on the device for me (see the image below).

Please note that in order this notification to get fired we need the following requirement fulfilled:
1. The application must be in background and the device should be locked (with black screen);
2. The application should reside in a state as described in point 1 for at least 3 minutes.
3. The Exposure Notification System should be turned on (Consent) and all requested permissions (locations services, bluetooth) should be granted.

![Screen Shot 2021-05-21 at 9 32 28 AM](https://user-images.githubusercontent.com/5631487/119094052-302aeb80-ba19-11eb-82b0-a849a22a3d13.png)
