### ISSUE TITLE
[FEATURE] Vaccinated processing update

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/safer-illinois-app#651]
**Re: Universities Monday 2021/05/24** / 2021-05-28

There have been a few requested changes from campus regarding how we’ll handle vaccinated status in the app.

We’d like users with effective vaccine data to be granted a “Green - Fully vaccinated” status. Those vaccinated users will not have to test to maintain building access,

Next Steps for vaccinated users would be:
“We have a verified record of your completed COVID-19 vaccination on file. Your vaccination status replaces testing for compliance and building access until further notice. Please get an on-campus COVID-19 test if you experience symptoms. Continue to monitor university communications for any changes to your testing policy.”

Users on campus can still get tested, and status should be updated from Green to Red if they get a positive test.

We’re also wanting to have users prompted to review their consent for “health provider test results and vaccine data” once the string is changed and the events start getting sent by McKinley. Perhaps this would be a good time to offer an opportunity to view the updated privacy notice (not published yet).

**Comment by isaac-galvan** [comment]
> We’d like users with effective vaccine data to be granted a “Green - Fully vaccinated” status. Those vaccinated users will not have to test to maintain building access,

@mihail-varbanov @pmarkhennessy We need the Green status description updated to "Fully vaccinated" please.  This is very important to maintain consistent language across all of the university's communications. Thanks!

**Comment by mihail-varbanov** [comment]
The green status description is updated to read "Fully vaccinated". This change is located in health rules JSON only. The updated 2.10 health rules are uploaded on dev, test and production.
