### ISSUE TITLE
[USABILITY] Update vaccine widget text and button target

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/safer-illinois-app#708]
Describe the usability issue
Please update the vaccine widget text to say:

> -COVID-19 vaccines are safe
-COVID-19 vaccines are effective
-COVID-19 vaccines allow you to safely do more
-COVID-19 vaccines build safer protection

Also, please update the "Make vaccination appointment" button to target https://vaccines.gov

This text and URL will replace the items in this screenshot:
![1- No vaccine taken events (1)](https://user-images.githubusercontent.com/11352701/134454139-efae2c46-06f4-48c9-a025-88b3b9ce13e8.png)

**Comment by mihail-varbanov** [comment]
Fixed in version 2.11.1
