### ISSUE TITLE
[BUG] App is crashing when user tap on Show Status Card 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#725]
**Describe the bug**
The safer app is crashing when the user taps the Show Status Card 

**To Reproduce**

1. Install the safer app
2. complete onboarding screen and proceed to Home screen with user role "University Student"
3. On the Home screen tap on "Show Status Card

**Actual Result**
The safer app is crashing

**Expected behavior**
The app should display the user status without crashing

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 2.11.3]

**Comment by mihail-varbanov** [comment]
I was not able to recreate this issue. Please check it again or provide a recreation scenario.

**Comment by mihail-varbanov** [comment]
BTW, yesterday all rokwire.illinois.edu services were very unstable, working occasionally and often being down. This might be the reason for app misbehavior.

**Comment by Priyaravi8** [comment]
Issue is resolved
