### ISSUE TITLE
Contents are duplicated on Provide feedback screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/safer-illinois-app#77]
**Describe the bug**
Contents are duplicated on Provide feedback screen.

**To Reproduce**
1. Install safer Illinois
2. Complete the onboarding process of the app.
3. Navigate to the Setting screen and tap on Submit feedback button
4. Provide Feedback screen is displayed

**Actual Result**
1. The content "To submit feedback, please use the form below" is duplicated. 
2. The email id and URL format is not followed for "consult@illinois.edu" and "go.illinois.edu/safer-help"

**Expected behavior**
Please remove the duplicate content and follow the Email id format, change the font to blue and URL format, text with a blue font with a hyperlink.

**Screenshots**
![feed](https://user-images.githubusercontent.com/26231179/91589687-cd8c3f80-e91f-11ea-8716-bc9026197b37.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 2.4.1]

**Comment by isaac-galvan** [comment]
I can take care of this @Priyaravi8 
Will update when it's fixed.

**Comment by isaac-galvan** [comment]
@Priyaravi8 please review the updated feedback form. Thanks!
